services:
  tr3-back: 
    build: 
      dockerfile: ./back/dev.Dockerfile
      context: .
    working_dir: /usr/src/app
    command: sh -c "npm install && nodemon -L index.js"
    volumes:
      - ./back:/usr/src/app
    ports:
      - "3020:3020"
    depends_on:
      - tr3-mysql
      - tr3-mongo
    networks:
      - tr3-network

  tr3-front:
    image: node:23-bullseye
    container_name: nuxt
    build:
      context: ./front-end/tr3-UnityProject
      dockerfile: develop.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./front-end/tr3-UnityProject:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    links:
      - tr3-back
    networks:
      - tr3-network

  tr3-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-bd:/data/db
    networks:
      - tr3-network

  tr3-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@tr3-mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - tr3-mongo
    networks:
      - tr3-network

  tr3-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tr3-Unity
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-bd:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - tr3-network

  tr3-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr3-mysql
    depends_on:
      - tr3-mysql
    networks:
      - tr3-network
  tr3-stats:
    build:
      context: .
      dockerfile: ./back/python/Dockerfile
    volumes:
      - ./back/python:/usr/src/app
    working_dir: /usr/src/app
    command: python stats.py
    depends_on:
      - tr3-mongo
    networks:
      - tr3-network


volumes:
  mysql-bd:
  mongo-bd:

networks:
  tr3-network:
    driver: bridge