services:
  tr3-back: 
    build: 
      dockerfile: ./back/dev.Dockerfile
      context: .
    working_dir: /usr/src/app
    command: sh -c "npm install && nodemon -L index.js"
    volumes:
      - ./back:/usr/src/app
    ports:
      - "3020:3020"
    depends_on:
      - tr3-mysql
      - tr3-mongo

  tr3-front:
    image: node:23-bullseye
    container_name: nuxt
    build:
      context: ./front-end/tr3-UnityProject
      dockerfile: develop.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./front-end/tr3-UnityProject:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    links:
      - tr3-back

  tr3-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-bd:/data/db

  tr3-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@tr3-mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - tr3-mongo

  tr3-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: tr3-Unity
    volumes:
      - mysql-bd:/var/lib/mysql:rw
      - ./bd/mysql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./bd/mysql/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
    ports:
      - 3306:3306

  tr3-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr3-mysql
    depends_on:
      - tr3-mysql

volumes:
  mysql-bd:
  mongo-bd: